# Generated by Django 2.2.5 on 2020-01-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_management', '0003_auto_20180830_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldreference',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
