# Generated by Django 2.2.5 on 2020-01-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0497_auto_20200108_1213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learningachievement',
            options={'ordering': ('order',)},
        ),
    ]
